version: "3"

services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbit-nerdstore
        environment:
            RABBITMQ_DEFAULT_USER: "nerdstore"
            RABBITMQ_DEFAULT_PASS: "nerdstore"

    sql-server:
        image: joanarfc/nerdstore-sql-server:latest
        container_name: nerdstore-sql-server
        build: 
            context: ../sql
            dockerfile: ./Dockerfile
        environment:
            SA_PASSWORD: "MeuDB@123"
            ACCEPT_EULA: "Y"     

    web-mvc:
        image: joanarfc/nerdstore-web-mvc-ecommerce:latest
        container_name: nerdstore-web-mvc-ecommerce
        build:
            context: ../src
            dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5001
        volumes: 
            - dpkeys:/var/data_protection_keys/         
        depends_on:
            - api-catalog
            - api-identity
            - api-customer
            - api-bff-compras

    api-identity:
        image: joanarfc/nerdstore-api-identity:latest
        container_name: nerdstore-api-identity    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Identity.API/Dockerfile  
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5101;http://+5102
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
            - dpkeys:/var/data_protection_keys/
        depends_on:
            - rabbitmq
            - sql-server
            
    api-shoppingcart:
        image: joanarfc/nerdstore-api-shoppingcart:latest
        container_name: nerdstore-api-shoppingcart
        build: 
            context: ../src
            dockerfile: ./services/NSE.ShoppingCart.API/Dockerfile      
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5201;http://+5202
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
            - dpkeys:/var/data_protection_keys/
        depends_on:
            - rabbitmq
            - api-identity
            - sql-server         

    api-catalog:
        image: joanarfc/nerdstore-api-catalog:latest
        container_name: nerdstore-api-catalog
        build: 
            context: ../src
            dockerfile: ./services/NSE.Catalog.API/Dockerfile
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5301;http://+5302
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
            - dpkeys:/var/data_protection_keys/
        depends_on:
            - rabbitmq
            - sql-server

    api-customer:
        image: joanarfc/nerdstore-api-customer:latest
        container_name: nerdstore-api-customer    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Customers.API/Dockerfile
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5401;http://+5402
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
            - dpkeys:/var/data_protection_keys/
        depends_on:
            - rabbitmq
            - api-identity
            - sql-server  

    api-bff-compras:
        image: joanarfc/nerdstore-api-bff-compras:latest
        container_name: nerdstore-api-bff-compras
        build: 
            context: ../src
            dockerfile: ./api gateways/NSE.Bff.Compras/Dockerfile  
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5501;http://+5502
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
            - dpkeys:/var/data_protection_keys/
        depends_on:
            - rabbitmq
            - api-identity
            - api-shoppingcart
            - api-payment
            - api-order
            
    api-payment:
        image: joanarfc/nerdstore-api-payment:latest
        container_name: nerdstore-api-payment    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Payments.API/Dockerfile
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5601;http://+5602
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
            - dpkeys:/var/data_protection_keys/
        depends_on:
            - rabbitmq
            - api-identity
            - api-order
            - sql-server
            
    api-order:
        image: joanarfc/nerdstore-api-order:latest
        container_name: nerdstore-api-order    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Orders.API/Dockerfile 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5701;http://+5702
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
            - dpkeys:/var/data_protection_keys/
        depends_on:
            - rabbitmq
            - sql-server
            - api-identity                    

    nerdstore-server:
        image: joanarfc/nerdstore-server:latest
        container_name: nerdstore-server    
        build: 
            context: ./
            dockerfile: ./nginx/Dockerfile 
        ports:
            - "8080:80"
            - "443:443"
        depends_on:
            - web-mvc

volumes:
    dpkeys: